options:
  prev_tag: "versio-prev-hotfix-test"

projects:
  - name: "versio"
    id: 0
    tag_prefix: ""
    labels: cargo
    changelog: "CHANGELOG.html"
    version:
      file: "Cargo.toml"
      toml: "package.version"
    hooks:
      post_write: cargo update --workspace

sizes:
  use_angular: true
  fail: ["*"]
