key: get-cargo
value:
  - name: Get cargo nightly
    uses: dtolnay/rust-toolchain@nightly
    with:
      components: rustfmt
  - name: Get cargo stable
    uses: dtolnay/rust-toolchain@stable
    with:
      components: clippy
  - name: Find paths
    id: cargo-find-paths
    run: 'echo ::set-output name=cargo-lock-glob::"${{ matrix.root }}"/**/Cargo.lock'
  - name: Cache cargo and target
    uses: actions/cache@v1
    with:
      path: |
        ~/.cargo/registry
        ~/.cargo/git
        ${{ matrix.root }}/target
      key: ${{ runner.os }}-cargo-${{ hashFiles(steps.cargo-find-paths.outputs.cargo-lock-glob) }}
