key: job-versio-checks
value:
  runs-on: ubuntu-latest
  if: SNIPPET_not-skip-ci
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - SNIPPET_versio-actions-install
    - name: Fetch history
      run: git fetch --unshallow
    - name: Check projects
      run: versio check
    - name: Output plan
      run: versio plan
