key: job-github-publish
value:
  needs: versio-release
  runs-on: ubuntu-latest
  environment: Build
  if: SNIPPET_not-skip-ci
  outputs:
    upload_url: ${{ steps.publish-to-github.outputs.upload_url }}
  steps: SNIPPET_steps-github-publish
