key: job-project-matrixes
value:
  runs-on: ubuntu-latest
  if: SNIPPET_not-skip-ci
  outputs:
    cargo-matrix: ${{ steps.find-cargo-matrix.outputs.matrix }}
    all-matrix: ${{ steps.find-all-matrix.outputs.matrix }}
  steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - SNIPPET_versio-actions-install
    - name: Find cargo matrix
      id: find-cargo-matrix
      run: 'echo "::set-output name=matrix::{\"include\":$(versio -l none info -l cargo -R -N)}"'
    - name: Find all matrix
      id: find-all-matrix
      run: 'echo "::set-output name=matrix::{\"include\":$(versio -l none info -a -R -N)}"'
