key: job-versio-release
value:
  needs:
    - cargo-checks
    - versio-checks
  runs-on: ubuntu-latest
  if: SNIPPET_not-skip-ci
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - SNIPPET_versio-actions-install
    - SNIPPET_get-cargo-minimal
    - name: Fetch history
      run: git fetch --unshallow
    - name: Generate release
      run: versio -l local release
    - name: Commit release
      run: git commit -am 'build(deploy): Versio manual update'
    - name: Push release
      run: git push
    - name: Push release tags
      run: git push --tags --force
