key: steps-github-publish
value:
  - name: Checkout release
    uses: actions/checkout@v2
    with:
      ref: main
  - SNIPPET_versio-actions-install
  - name: Find version
    id: find-version
    run: 'echo ::set-output name=version::$(versio -l none info -i 0 -F | jq -r ''.[0].full_version'')'
  - name: Publish to GitHub
    id: publish-to-github
    uses: actions/create-release@v1
    with:
      tag_name: ${{ steps.find-version.outputs.version }}
      release_name: (TODO) RELEASE FOR ${{ steps.find-version.outputs.version }}
      body: |
        (TODO) SUMMARY
        - (TODO) FEATURE1

        New to Versio? The [repository](https://github.com/chaaz/versio) is the best place to learn about Versio and what it can do. If you want to report a bug or request a feature, you can do so at our [Issues](https://github.com/chaaz/versio/issues) link, but we ask you first read the [Troubleshooting](https://github.com/chaaz/versio/blob/main/docs/troubleshooting.md) page learn about problems and their solutions.

        DEPENDENCIES:

        On MacOS and Linux, you must have GPG tools installed. These tools are installed by default on most distributions of Linux and MacOS. If you can run `git`, then you probably have the necessary tools already installed.

        On Windows, you need to install the GpgME package, which is available [here](https://gnupg.org/ftp/gcrypt/binary/gnupg-w32-2.3.1_20210420.exe) (Signature and checksum available from its [parent directory](https://gnupg.org/ftp/gcrypt/binary/)).

        If you have any questions, you should view the [Dependency page](https://github.com/chaaz/versio/blob/main/docs/dependencies.md) for information about installing and testing dependencies.

        INSTALLATION: 

        To install, follow the instructions for your platform; some files might be zipped for improved download speed. For example, on MacOS you can do something like this (assuming `~/bin` exists and is in your PATH):

        ```sh
        curl -L https://github.com/chaaz/versio/releases/download/${{ steps.find-version.outputs.version }}/versio__x86_64-apple-darwin -o ~/bin/versio
        chmod +x ~/bin/versio
        ```

        **MacOS:** download `versio__x86_64-apple-darwin`, copy to `versio` in your PATH.
        **GNU Linux 64:** download `versio__x86_64-unknown-linux-gnu`, copy to `versio` in your PATH.
        **Windows:** download `versio__x86_64-pc-win32.exe`, copy to `versio.exe` in your %PATH.
      draft: true
      prerelease: false
      commitish: main
